NewIntense/NewIntense/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

admin.site.site_header = "Intense Placement"
admin.site.site_title = "Intense Placement"
admin.site.index_title = "Intense Placement"

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('account/' , include('account.urls')),
     path('reset_password/', 
    auth_views.PasswordResetView.as_view(template_name = "password_reset.html"),
    name = 'reset_password'),
    path('reset_password_sent/', 
    auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), name = 'password_reset_done'),

    path('reset/<uidb64>/<token>', 
    auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"), name = 'password_reset_confirm'),
       
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name = "password_reset_done.html"), name = 'password_reset_complete') ,

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NewIntense/account/urls.py
from django.urls import path ,include

from .views import candidateViwe , partnerView,accounts

# from . import views 

app_name = 'account'
urlpatterns = [
    # path('' , main.homepage , name = 'homepage'),
    path('login/' , accounts.loginpage , name = 'login'),
    path('loginp/' , accounts.loginpageP , name = 'loginp'),
    path('logout/' , accounts.logoutuser, name='logout'),
    path('candidateReg/', candidateViwe.candidateReg.as_view() , name = 'candidateReg'),
    path('candidateDash/', accounts.candidate_dash , name = 'candidate_dash'),
    path('partnerDash/', accounts.partner_dash , name = 'partner_dash'),
    path('partnerreg/', partnerView.partnerReg.as_view() , name = 'partnerReg'),
    path('patapply/', accounts.patapply , name = 'patapply'),
    path('candapply/', accounts.candapply , name = 'candapply'),
    path('updateCandidate/', candidateViwe.candidateUpdate , name = 'updateCandidate'),
    path('updatePartner/', partnerView.partnerUpdate , name = 'partnerupdate'),
]

NewIntense/main/urls.py
from django.urls import path
from . import views
from .views import *


app_name = "main"
urlpatterns = [
	path('',views.homepage , name = "homepage"),
	path('about/' ,views.about , name = "about"),
	path('employer/', views.employer, name = "employer"),
    path('contact/', views.contact, name = "contact"),
	# path('partner/', views.partner, name = "partner"),
    # path('log_sign/',views.log_sign , name= "log_sign"), 
    # path('register/', views.register ,  name = "register"),
    # path("candidate.html", views.candidate, name='candidate'), 
    path("jobs/", views.jobs, name='jobs'), 
    path("patcomm/", views.patcomm, name='patcomm'),
    # path("apply/", ApplyView.as_view(), name='apply'), 
    # path("patcomm.html", views.apply, name='patcomm'), 
    path('apply/<int:pk>/', views.apply, name = 'apply'),
    path('applyp/<int:pk>/', views.applyp, name = 'applyp'),
    path('faq/' , views.faq , name = 'faq'),
]

NewIntense/main/forms.py
from django import forms
from .models import Contact,Apply ,Enquiry,ApplyP
from phonenumber_field.formfields import PhoneNumberField
from django.forms.utils import ValidationError
from django.core.validators import RegexValidator
from django.core import validators

GND_CHOICES = (
   ('M', 'Male'),
   ('F', 'Female')
)

numeric = RegexValidator(r'^[0-9+]', 'Only digit characters.')

class ContactForm(forms.ModelForm):
    message= forms.CharField(required=True,widget=forms.Textarea(attrs={'rows': 4,'cols':23}))
    class Meta:
        model = Contact
        fields = [
            'name',
            'mail',
            'contact_Number',
            'message']
    def clean(self):
        name=self.cleaned_data.get("name")
        if (name.isdigit()) :
            raise forms.ValidationError("Name should not contain digit")

        

class ApplicationForm(forms.ModelForm):
        class Meta:
           model = Apply
           fields = [
               'name',
               'email',
               'contact_Number',
               'gender',
               'current_City',
               'upload_Resume']
        def clean(self):
            name=self.cleaned_data.get("name")
            if (name.isdigit()):
               raise forms.ValidationError("Name should not contain digit")

    
        
class ApplicationFormP(forms.ModelForm):
        class Meta:
           model = ApplyP
           fields = [
               'name',
               'email',
               'contact_Number',
               'gender',
               'current_City',
               'upload_Resume']
        def clean(self):
           name=self.cleaned_data.get("name")
           if (name.isdigit()) :
               raise forms.ValidationError("Name should not contain digit")

        

class EnquiryForm(forms.ModelForm):
        class Meta :
           model = Enquiry
           fields = [
               'name',
               'company',
               'post',
               'mail',
               'contact_Number',
               'city',
               'description'
           ]
        def clean(self):
           name=self.cleaned_data.get("name")
           if (name.isdigit()):
               raise forms.ValidationError("Name should not contain digit")

       
   

NewIntense/account/views/partnerView.py
from ..models import User
from django.contrib.auth import login
from ..forms import partnerRegForm,EditProfileForm , EditPartnerProfile
from django.views.generic import CreateView
from django.shortcuts import render , redirect

class partnerReg(CreateView):
    model = User
    form_class = partnerRegForm
    template_name = 'partnerReg.html'

    def get_context_data(self , **kwargs):
        kwargs['user_type'] = 'partner'
        return super().get_context_data(**kwargs)

    def form_valid(self , form):
        user = form.save()
        return redirect('account:loginp')

def partnerUpdate(request):
    if request.method == 'POST':
        u_form = EditProfileForm(request.POST , instance = request.user)
        p_form = EditPartnerProfile(request.POST, instance = request.user.partner)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            return redirect('account:partner_dash')
    else:
        u_form = EditProfileForm(instance = request.user)
        p_form = EditPartnerProfile(instance = request.user.partner)
     
    context = {
        'u_form' : u_form,
        'p_form' : p_form
    }
    
    return render(request , 'userUpdatePartner.html' , context)

NewIntense/main/views.py
from django.shortcuts import render, redirect
from .models import Job , Apply
from django.contrib import messages
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from .forms import ContactForm,ApplicationForm ,EnquiryForm,ApplicationFormP
from django.core.files.storage import FileSystemStorage
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse_lazy
from django.core.paginator import Page,Paginator,PageNotAnInteger,EmptyPage

from django.views.generic import CreateView, ListView

from rest_framework import viewsets, mixins, status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from .serializers import *
from rest_framework.generics import ListAPIView, CreateAPIView

from rest_framework.views import APIView 



def homepage(request):
	if request.user.is_authenticated:
		if request.user.is_partner:
			jobArr= Commission.objects.all()
			page = request.GET.get('page', 1)
			paginator = Paginator(jobArr, 6)
			try:
				jjob = paginator.page(page)
			except PageNotAnInteger:
				jjob = paginator.page(1)
			except EmptyPage:
				jjob = paginator.page(paginator.num_pages)
			jobArr1=Commission.objects.order_by().values('job_title').distinct()
			jobArr2=Commission.objects.order_by().values('city').distinct()
			role_val = request.GET.get('role')
			city_val = request.GET.get('city')
			district_val = request.GET.get('role')
			if role_val !='' and role_val is not None:

				jjob = jobArr.filter(job_title__icontains = role_val) 
			elif city_val !='' and city_val is not None:
				jjob = jobArr.filter(city__icontains = city_val) 
		else :
			jobArr= Job.objects.all()
			page = request.GET.get('page', 1)
			paginator = Paginator(jobArr, 18)
			try:
				jjob = paginator.page(page)
			except PageNotAnInteger:
				jjob = paginator.page(1)
			except EmptyPage:
				jjob = paginator.page(paginator.num_pages)
			jobArr1=Job.objects.order_by().values('job_title').distinct()
			jobArr2=Job.objects.order_by().values('city').distinct()
			role_val = request.GET.get('role')
			city_val = request.GET.get('city')
			district_val = request.GET.get('role')
			if role_val !='' and role_val is not None :
				jjob = jobArr.filter(job_title__icontains = role_val)
			elif city_val !='' and city_val is not None :
				jjob = jobArr.filter(city__icontains = city_val) 
	else :
			jobArr= Job.objects.all()
			page = request.GET.get('page', 1)
			paginator = Paginator(jobArr, 18)
			try:
				jjob = paginator.page(page)
			except PageNotAnInteger:
				jjob = paginator.page(1)
			except EmptyPage:
				jjob = paginator.page(paginator.num_pages)
			jobArr1=Job.objects.order_by().values('job_title').distinct()
			jobArr2=Job.objects.order_by().values('city').distinct()
			role_val = request.GET.get('role')
			city_val = request.GET.get('city')
			district_val = request.GET.get('role')
			if role_val !='' and role_val is not None :
				jjob = jobArr.filter(job_title__icontains = role_val)
			elif city_val !='' and city_val is not None :
				jjob = jobArr.filter(city__icontains = city_val) 

	return render(request = request,
					template_name = "home.html",
					 context = {
						 "jjob" : jjob,
					 	'jobArr1' : jobArr1,
						'jobArr2' : jobArr2,}
					)
def about(request):
	return render(request = request,
		 		  template_name = "about.html",
				  # context = {"jobs" : Job.objects.all}
				  )

def faq(request):
	return render(request= request,
			template_name = "faq.html",
	)
def employer(request):
	if request.method=='POST':
		form = EnquiryForm(request.POST)
		if form.is_valid():
			form.save()
			messages.info(request,'Data Submitted Successfully') 
		else :
			messages.error(request,'Enter Correct Data') 

	form = EnquiryForm()
	return render(request,'employer.html',{'form':form} )
	# return render(request = request,
	# 			  template_name = "employer.html",
	# 			  # context = {"jobs" : Job.objects.all}
	# 			  )

def contact(request):
	if request.method=='POST':
		message_name = request.POST['name']
		message_email = request.POST['mail']
		# message_contact = request.POST['contact']
		message = request.POST['message']

		send_mail(
			'Message from '+message_name, #subject
			message +' Send a reply to this query at : '+message_email,  #message
			message_email ,  # from emails
			['intenseplacement.ip@gmail.com'],
		)
		messages.info(request , message_name)
		form = ContactForm(request.POST)
		if form.is_valid():
			form.save()
			messages.info(request,'Thanks ,We have recieved your email and will respond shortly...') 

		else :
			messages.error(request,'Enter Correct Data') 

	form = ContactForm()
	return render(request,'contact.html',{'form':form} )
	# return render(request = request,
	# 			  template_name = "contact.html",
	# 			  # context = {"jobs" : Job.objects.all}
	# 			  )
	
@login_required(login_url= 'account:login')
def jobs(request):
	jobArr= Job.objects.all()
	page = request.GET.get('page', 1)
	paginator = Paginator(jobArr, 18)
	try:
		jjob = paginator.page(page)
	except PageNotAnInteger:
		jjob = paginator.page(1)
	except EmptyPage:
		jjob = paginator.page(paginator.num_pages)
	jobArr1=Job.objects.order_by().values('job_title').distinct()
	jobArr2=Job.objects.order_by().values('city').distinct()
	role_val = request.GET.get('role')
	city_val = request.GET.get('city')
	district_val = request.GET.get('role')
	if role_val !='' and role_val is not None :
		jjob = jobArr.filter(job_title__icontains = role_val)
	elif city_val !='' and city_val is not None :

		jjob = jobArr.filter(city__icontains = city_val) 

	if not jobArr :
		messages.error(request,'Currently there are 0 jobs')
	context = {
		'jobArr' : jobArr,
		'jobArr1' : jobArr1,
		'jobArr2' : jobArr2,
		'jjob' : jjob
	}
	return render(request= request, 
				  template_name = "jobs.html",
				  context = context)

@login_required(login_url='account:login')
def apply(request,pk):
	jjob = Job.objects.get(pk=pk)
	cc=Candidate.objects.get(user =  request.user)
	if Apply.objects.filter(job = jjob, candidate = cc).exists():
		messages.error(request,'You have already applied for this job')
	else :
		if request.method == 'POST':
			form = ApplicationForm( request.POST , request.FILES )
			if form.is_valid():
				post = form.save(commit = False)
				post.candidate = Candidate.objects.get(user =  request.user)
				post.job = Job.objects.get(pk = pk )
				post.save()
				messages.success(request,' You have applied  successfully for this job')
			else :
				messages.error(request,'Enter Correct Data') 

	form = ApplicationForm()
	return render(request,'apply.html',{'form':form} )
	# return render(request = request,
	# 			  template_name = "apply.html",
	# 			  # context = {"jobs" : Job.objects.all}
	# 			  )

@login_required(login_url='account:loginp')
def applyp(request,pk):
	# initial_data={
	# 	'candidate': request.user.username,
	# 	'job' : jjob.job_title
	# }
	if request.method == 'POST':
		form = ApplicationFormP( request.POST , request.FILES )
		if form.is_valid():
			post = form.save(commit = False)
			#post.candidate = request.user.username
			post.partner = Partner.objects.get(user =  request.user)
			post.job = Commission.objects.get(pk = pk )
			post.save()
			messages.success(request,' You have applied  successfully for this job')
			# form.save()
		else :
			messages.error(request,'Enter Correct Data') 

	form = ApplicationFormP()
	return render(request,'applp.html',{'form':form} )

@login_required(login_url='account:loginp')
def patcomm(request):
	jobArr= Commission.objects.all()
	page = request.GET.get('page', 1)
	paginator = Paginator(jobArr, 6)
	try:
		jjob = paginator.page(page)
	except PageNotAnInteger:
		jjob = paginator.page(1)
	except EmptyPage:
		jjob = paginator.page(paginator.num_pages)
	jobArr1=Commission.objects.order_by().values('job_title').distinct()
	jobArr2=Commission.objects.order_by().values('city').distinct()
	role_val = request.GET.get('role')
	city_val = request.GET.get('city')
	district_val = request.GET.get('role')
	if role_val !='' and role_val is not None:

		jjob = jobArr.filter(job_title__icontains = role_val) 
	elif city_val !='' and city_val is not None:
		jjob = jobArr.filter(city__icontains = city_val) 
	if not jobArr :
		messages.error(request,'Currently there are 0 jobs')
	context = {
		'jobArr' : jobArr,
		'jobArr1' : jobArr1,
		'jobArr2' : jobArr2,
		'jjob' : jjob
	}

	return render(request = request,
				  template_name = "pat_com.html",
				  context = context
				  )


class JobViewSet(viewsets.ReadOnlyModelViewSet):
	serializer_class = JobSerializer
	queryset = serializer_class.Meta.model.objects.all()


class ApplyJobApiView(CreateAPIView):
	serializer_class = ApplicantSerializer
	http_method_names = [u'post']
	permission_classes = [IsAuthenticated]

	def create(self , request , *args , **kwargs):
		serializer = self.get_serializer(data = request.data)
		serializer.is_valid(raise_exception = True)
		self.perform_create(serializer)
		headers = self.get_success_headers(serializer.data)
		return Response(serializer.data , status = status.HTTP_201_CREATED , headers = headers)

class ApplyAPIView(APIView):
	
	def get(self , request):
		apply = Apply.objects.all()
		serializer = ApplicantSerializer(employer , many = True)
		return Response(serializer.data)

NewIntense/main/templates/home.html
{% load static %}

<!DOCTYPE html>
<head>
    <title>Intense placement</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/homeStyle.css' %}">

    <link rel="stylesheet" href="{% static 'styles/bootstrap-4.5.0/css/bootstrap.css' %}">
    <link href="{% static 'plugins/fontawesome-free-5.13.0-web/css/fontawesome.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/fontawesome-free-5.13.0-web/css/brands.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/fontawesome-free-5.13.0-web/css/solid.css' %}" rel="stylesheet">

	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" ></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" ></script>
	<script src="{% static 'styles/bootstrap-4.5.0/js/bootstrap.min.js' %}" ></script>
</head>
<body>

<section id="header">
    <div class="menu-bar">
      <nav class="navbar navbar-expand-lg navbar-light ">
          <a class="navbar-brand" href="#">
            <img src="{% static 'img/ipLogo.png' %}">
          </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto" >
          <li class="nav-item ">
            <a class="nav-link " href="{% url 'main:homepage' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="/about/">About Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="/contact/">Contact Us</a>
          </li>
          {% if user.is_authenticated %}
            {% if user.is_candidate %}
              <li class="nav-item">
                <a class="nav-link  " href="/jobs/">Jobs</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.username }}</a>
                <div class="dropdown-menu menu-bar" aria-labelledby="navbarDropdown">
                <a class="dropdown-item nav-link" href="{% url 'account:candidate_dash' %}" id = "candidate_dashboard"  href="#">Profile</a>
                <a class="dropdown-item nav-link" href="{% url 'account:logout' %}" id = "logoutButton" href="#">Logout</a>
              </div>
            </li>
            {% elif user.is_partner %}
              <li class="nav-item">
                <a class="nav-link  " href="/patcomm/">Partner's Zone</a>
              </li>
              <li  class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.username }}</a>
              <div class="dropdown-menu menu-bar" aria-labelledby="navbarDropdown" >
                <a class="dropdown-item nav-link" href="{% url 'account:partner_dash' %}" id = "candidate_dashboard" >Profile</a>
                <a class="dropdown-item nav-link" href="{% url 'account:logout' %}" id = "logoutButton" >Logout</a>
              </div>
              </li>
            {% endif %}
          {% else %}
          <li class="nav-item">
            <a class="nav-link " href="/employer/">Employer's Zone</a>
          </li> 
          <li class="nav-item">
            <a class="nav-link  " href="{% url 'account:partnerReg' %}">Partner's Zone</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Login/SignUp
            </a>
            <div class="dropdown-menu menu-bar" aria-labelledby="navbarDropdown">
              <a class="dropdown-item nav-link"  id = "login_Button"  href="{% url 'account:login' %}">For Candidate</a>
              <a class="dropdown-item nav-link"   id = "login_Button" href="{% url 'account:loginp' %}">For Partner</a>
            </div>
            </li>
            {% endif %}
        </ul>
          </div>
        </nav>
    </div> 
  
    <div class="banner text-center">
      <h1 class="  text-white text-center"><b>Design Your Career With Intense<b></h1>
        {% if user.is_authenticated %}

        {% else %}
        <h3 class=" text-center text-white">Looking For a Job ! Join us today</h3>
        <p class=" text-center text-white"><br> <a class="btn btn-primary text-white"  id = "login_Button" href="{% url 'account:candidateReg' %}">I am candidate</a></p> 
        {% endif %}
      </div>

</section>


<div class="search-job text-center">
    <div>
        <h1 class="text-center text-white">Find the best job near you</h1>
        <h4 class="text-center text-white"><span style="color:rgb(246, 250, 3)">1,00,000</span> active job vacancies to grab. </h4>
    </div>
    {% if user.is_authenticated %}
      {% if user.is_candidate %}
        <form action="/jobs/" method="get" id ="findform">
          <div class="form-group">
          <select class="form-control" id="sel1" name="role">
              <option disabled selected>Job Role</option>
              {% for job in jobArr1 %}
              <option>{{job.job_title}}</option>
              {% endfor %}
          </select>
          <select class="form-control" id="sel1" name="city">
              <option disabled selected>City</option>
              {% for job in jobArr2 %}
              <option>{{job.city}}</option>
              {% endfor %}
          </select>
          
          <button type="submit" class="btn btn-primary " onclick="submitForm()"> Search</button>
        </form>
      {% elif user.is_partner %}
      <form action="/patcomm/" method="get" id ="findform">
        <div class="form-group">
        <select class="form-control" id="sel1" name="role">
            <option disabled selected>Job Role</option>
            {% for job in jobArr1 %}
            <option>{{job.job_title}}</option>
            {% endfor %}
        </select>
        <select class="form-control" id="sel1" name="city">
            <option disabled selected>City</option>
            {% for job in jobArr2 %}
            <option>{{job.city}}</option>
            {% endfor %}
        </select>
        
        <button type="submit" class="btn btn-primary " onclick="submitForm()"> Search</button>
      </form>
    {% endif %}
  {% else %}
    <form action="/jobs/" method="get" id ="findform">
      <div class="form-group">
      <select class="form-control" id="sel1" name="role">
          <option disabled selected>Job Role</option>
          {% for job in jobArr1 %}
          <option>{{job.job_title}}</option>
          {% endfor %}
      </select>
      <select class="form-control" id="sel1" name="city">
          <option disabled selected>City</option>
          {% for job in jobArr2 %}
          <option>{{job.city}}</option>
          {% endfor %}
      </select>
      
      <button type="submit" class="btn btn-primary " onclick="submitForm()"> Search</button>
    </form>
  {% endif %}
     
 </div>
  
</div>


  <section>
    <h2 class="text-center"><b>Top Job Roles</b></h2>
    <div class="card-deck" >
		<div class="card border-info shadow p-3 mb-5 rounded" style="height:10rem;">
			<i class="card-img-top fas fa-headset fa-5x "></i>
		  <div class="card-body">
			<h5 class="card-title text-center">BPO</h5>
		  </div>
		</div>
		<div class="card border-info shadow p-3 mb-5 rounded " style="height:10rem;">
			<i class=" card-img-top fas fa-laptop-code fa-5x"></i>
			<div class="card-body">
				<h5 class="card-title text-center">Data Entry</h5>
		  	</div>
		</div>
		<div class="card border-info shadow p-3 mb-5 rounded " style="height:10rem;">
			<i class=" card-img-top fas fa-chart-line fa-5x"></i>
			<div class="card-body">
				<h5 class="card-title text-center">Marketing</h5>
		  	</div>
		</div>
		<div class="card border-info shadow p-3 mb-5 rounded" style="height:10rem;">
			<i class=" card-img-top fas fa-landmark fa-5x"></i>
			<div class="card-body">
			  <h5 class="card-title text-center">Engineer</h5>
			</div>
		</div>
		<div class="card border-info shadow p-3 mb-5 rounded "style="height:10rem;">
			<i class=" card-img-top fas fa-file-invoice-dollar fa-5x"></i>
			<div class="card-body">
			  <h5 class="card-title text-center">Accountant</h5>
			</div>
		</div>
	</div>
	<div>
    <center>
      {% if user.is_authenticated %}
        {% if user.is_candidate %}
          <a class="btn btn-primary text-white"  href="/jobs/">View Job Roles</a>
        {% elif user.is_partner %}
          <a class="btn btn-primary text-white"  href="/patcomm/">View Job Roles</a>
        {% endif %}
      {% else %}
      <a class="btn btn-primary text-white"  href="/jobs/">View Job Roles</a>

      {% endif %}
    </center>
  </div>
	</section> 
<br>
<br>

<footer class="page-footer font-small pt-4 pl-md-5">
    <div class="container-fluid text-center text-md-left">
      <div class="row">
        <div class="col-md-4 mt-md-0 mt-4 text-left" >
          <h5 class="text-uppercase" id="desc">Intense Placement</h5>
          <p id = "desc">Our Comapny provides you hastle free recruiting and save candidates from being cheated .Our main motto is to save each and every candidate from being cheated by fraud consultants or recruiters who asks money before getting the job. </p>
        </div>
        <!-- <hr class="clearfix w-100 d-md-none pb-3"> -->
        <div class="col-md-4 d-none d-lg-block d-xl-block text-center" >
          <h5 class="text-uppercase">Quick Links</h5>
          <ul class="list-unstyled">
            <li>
              <a href="{% url 'main:homepage' %}">Home</a>
            </li>
            <li>
              <a href="/contact/">Contact us</a>
            </li>
            <li>
              <a href="/about/">About us</a>
            </li>
            <li>
              <a href="/faq/">FAQs</a>
            </li>
            
          </ul>
        </div> 
        <div class="col-3 col-md-4 pl-md-4 d-none d-lg-block d-xl-block text-left">
          <h5 class="text-uppercase">Intense Placement </h5>
          <p id = "desc">Our Comapny is creating Entrepreneurs.Because of our portal we are connecting many of the Genuine Consultants , Recruiters or Freelancers to Big MNC's which previously they don't get empanel with,because of their major compliance issue . </p>
        </div>
      </div>
    </div>
    <div class="container " style="height: 100px;">
        <div class="row">
            <div class="col-md-12 py-3">
            <h5 class= "pb-2 text-center">Follow Us</h5>
            <div class="mb-2 text-center">
              <a href = "https://www.facebook.com/Intense-Placement-Private-Limited-102928834808269/" class="fb-ic" style="color: rgb(255, 255, 255);">
                <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
              </a>
              <a href = "#" class="tw-ic" style="color:  rgb(255, 255, 255);">
                <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
              </a>
              <a href = "https://www.linkedin.com/company/intense-placement-private-limited" class="li-ic" style="color:  rgb(255, 255, 255);">
                <i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
              </a>
              <a href = "https://www.instagram.com/invites/contact/?i=zmndwoirzzee&utm_content=hftfvyr" class="ins-ic" style="color:  rgb(255, 255, 255);">
                <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
              </a>
            </div>
          </div>
        </div>
    </div>
    <div class="footer-copyright text-center py-2">
      <h6> <a href="mailto:devvarrior@gmail.com" class="text-white" style="float: left;"><i class="fas fa-code"></i> Website credits : Devvarrior <i class="fas fa-code"></i></a> <p style="float: right;">© 2020 Copyright:Intense Placement</p></h6>
      <br>
    </div>
</footer>
<script src="{% static  'js/homeJS.js' %}"></script>
</body>
</html>