NewIntense/NewIntense/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

admin.site.site_header = "Intense Placement"
admin.site.site_title = "Intense Placement"
admin.site.index_title = "Intense Placement"

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('account/' , include('account.urls')),
     path('reset_password/', 
    auth_views.PasswordResetView.as_view(template_name = "password_reset.html"),
    name = 'reset_password'),
    path('reset_password_sent/', 
    auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), name = 'password_reset_done'),

    path('reset/<uidb64>/<token>', 
    auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"), name = 'password_reset_confirm'),
       
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name = "password_reset_done.html"), name = 'password_reset_complete') ,

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NewIntense/account/urls.py
from django.urls import path ,include

from .views import candidateViwe , partnerView,accounts

# from . import views 

app_name = 'account'
urlpatterns = [
    # path('' , main.homepage , name = 'homepage'),
    path('login/' , accounts.loginpage , name = 'login'),
    path('loginp/' , accounts.loginpageP , name = 'loginp'),
    path('logout/' , accounts.logoutuser, name='logout'),
    path('candidateReg/', candidateViwe.candidateReg.as_view() , name = 'candidateReg'),
    path('candidateDash/', accounts.candidate_dash , name = 'candidate_dash'),
    path('partnerDash/', accounts.partner_dash , name = 'partner_dash'),
    path('partnerreg/', partnerView.partnerReg.as_view() , name = 'partnerReg'),
    path('patapply/', accounts.patapply , name = 'patapply'),
    path('candapply/', accounts.candapply , name = 'candapply'),
    path('updateCandidate/', candidateViwe.candidateUpdate , name = 'updateCandidate'),
    path('updatePartner/', partnerView.partnerUpdate , name = 'partnerupdate'),
]

NewIntense/main/urls.py
from django.urls import path
from . import views
from .views import *


app_name = "main"
urlpatterns = [
	path('',views.homepage , name = "homepage"),
	path('about/' ,views.about , name = "about"),
	path('employer/', views.employer, name = "employer"),
    path('contact/', views.contact, name = "contact"),
	# path('partner/', views.partner, name = "partner"),
    # path('log_sign/',views.log_sign , name= "log_sign"), 
    # path('register/', views.register ,  name = "register"),
    # path("candidate.html", views.candidate, name='candidate'), 
    path("jobs/", views.jobs, name='jobs'), 
    path("patcomm/", views.patcomm, name='patcomm'),
    # path("apply/", ApplyView.as_view(), name='apply'), 
    # path("patcomm.html", views.apply, name='patcomm'), 
    path('apply/<int:pk>/', views.apply, name = 'apply'),
    path('applyp/<int:pk>/', views.applyp, name = 'applyp'),
    path('faq/' , views.faq , name = 'faq'),
]

NewIntense/account/models.py
# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.html import escape, mark_safe

GND_CHOICES = (
   ('M', 'Male'),
   ('F', 'Female')
)
ORG_CHOICES = (
   ('PA', 'Placement Agency'),
   ('FR', 'Freelancer'),
   ('N','NGO'),
   ('TI','Training Institute'),
   ('CC','Cyber Cafe'),
   ('CLG','College'),
)

class User(AbstractUser):
    is_candidate = models.BooleanField(default = False)
    is_partner = models.BooleanField(default = False)
    

class Candidate(models.Model):
    user = models.OneToOneField(User,on_delete = models.CASCADE , primary_key = True)
    # first_name=models.CharField(max_length=20)
    # last_name=models.CharField(max_length=20)
    # email=models.EmailField()
    phone_no = models.CharField(max_length = 10)
    gender = models.CharField(choices=GND_CHOICES, max_length=128,null=True)
    father_name=models.CharField(max_length=50)
    education=models.CharField(max_length=100)
    PAN_number=models.CharField(max_length=10)
    Aadhar_number=models.CharField(max_length=13)
    location = models.CharField(max_length = 20)
    last_salary = models.CharField(max_length = 50 ,default="Not Applicable")
    last_company= models.CharField(max_length = 50,default='Not Applicable')
    
    def __str__(self):
        return self.user.username
    
class Partner(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key = True)
    # first_name=models.CharField(max_length=20)
    # last_name=models.CharField(max_length=20)
    # email=models.EmailField()
    organisation_type = models.CharField(choices=ORG_CHOICES, max_length=128,null=True)
    organisation_name = models.CharField(max_length = 20)
    organisation_location = models.CharField(max_length = 20)
    phone_no = models.CharField(max_length = 10)
    experience = models.CharField(max_length = 10)
    def __str__(self):
        return self.user.username

NewIntense/account/views/accounts.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from django.contrib import messages
from django.contrib.auth import authenticate , login , logout
from django.contrib.auth.decorators import login_required 
from ..decorators import unauthenticated_user
from ..models import Candidate,Partner
from main.models import Apply , Job, Commission,ApplyP
from django.core.paginator import Page,Paginator,PageNotAnInteger,EmptyPage

# def home(request):
#     # if request.user.is_authenticated:
#     #     if request.user.is_partner:
#     #         return redirect('homePar')
#     #     else:
#     #         return redirect('homeCan')
#     # else:
#         return render(request, 'home.html')

def loginpage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(request, username=username , password = password)
        if user is not None and user.is_candidate == True :
            login(request , user)
            return redirect('account:candidate_dash')
        else:
            messages.info(request, 'Username or Password is incorrect')
            return render(request , 'login.html')
    return render(request = request,
            template_name = 'login.html' 
        )

def loginpageP(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(request, username=username , password = password)
        if user is not None and user.is_partner == True:
            login(request , user)
            return redirect('account:partner_dash')
        else:
            messages.info(request, 'Username or Password is incorrect')
            return render(request , 'loginp.html')
    return render(request = request,
            template_name = 'loginp.html' 
        )
def logoutuser(request):
    logout(request)
    return redirect('main:homepage')

@login_required(login_url = 'account:login')
def candidate_dash(request):
   
    return render(request = request , template_name = 'candidateDash.html')


@login_required(login_url = 'account:login')
def candapply(request):
    # candidate = Candidate.objects.get(user_id = pk)
    candidateJ = Candidate.objects.get(user =  request.user)
    applicant = Apply.objects.filter(candidate = candidateJ)
    # jobs = Apply.objects.filter(candidate =request.user.id)
    job_id = applicant.values("job")
    jobs = Job.objects.filter(id__in = job_id).values() 
    page = request.GET.get('page', 1)
    paginator = Paginator(jobs, 18)
    try:
        jjob = paginator.page(page)
    except PageNotAnInteger:
        jjob = paginator.page(1)
    except EmptyPage:
        jjob = paginator.page(paginator.num_pages)
    if not jobs :
        messages.error(request,'You have 0 Applications')
    context = { 'jobs' :jobs ,
                'jjob' :jjob
              }
    return render(request = request , template_name = 'cand_apply.html' , context = context)


@login_required(login_url = 'account:loginp')
def partner_dash(request):

    return render(request = request , template_name = 'partnerDash.html')


@login_required(login_url = 'account:loginp')
def patapply(request):
    try :
        partnerJ = Partner.objects.get(user =  request.user)
    except Partner.DoesNotExist : 
        partnerJ = None
    #applicant = ApplyP.objects.filter(partner = partnerJ)
    job = ApplyP.objects.filter(partner =request.user.id)
    #job_id = applicant.values("job")
    #jobs = Commission.objects.filter(id__in = job_id).values()
    #context = { 
       # 'jobs' :jobs ,
       # 'applicant': applicant
    #}
    applicant = ApplyP.objects.filter(partner = partnerJ).select_related('job')
    page = request.GET.get('page', 1)
    paginator = Paginator(applicant, 18)
    try:
        jjob = paginator.page(page)
    except PageNotAnInteger:
        jjob = paginator.page(1)
    except EmptyPage:
        jjob = paginator.page(paginator.num_pages)
    if not applicant :
        messages.error(request,'You have 0 Applications')
    context = { 
        'jjob' :jjob ,
        'applicant': applicant
    }
    return render(request = request , template_name = 'pat_apply.html',context=context)
    

NewIntense/account/views/candidateViwe.py
from django.shortcuts import render , redirect
from ..forms import candidateRegForm , EditProfileForm , EditCandidateProfile
from ..models import User , Candidate
from django.views.generic import CreateView , UpdateView

# from django.contrib.auth import authenticate , login , logout


class candidateReg(CreateView):
    model = User
    form_class = candidateRegForm
    template_name = 'candidateReg.html'

    def get_context_data(self , **kwargs):
        kwargs['user_type'] = 'candidate'
        return super().get_context_data(**kwargs)
    
    def form_valid(self , form):
        user = form.save()
        return redirect('account:login')  
        # return redirect('account:home')


def candidateUpdate(request):
    if request.method == 'POST':
        u_form = EditProfileForm(request.POST , instance = request.user)
        c_form = EditCandidateProfile(request.POST, instance = request.user.candidate)
        if u_form.is_valid() and c_form.is_valid():
            u_form.save()
            c_form.save()
            return redirect('account:candidate_dash')
    else:
        u_form = EditProfileForm(instance = request.user)
        c_form = EditCandidateProfile(instance = request.user.candidate)
     
    context = {
        'u_form' : u_form,
        'c_form' : c_form
    }
    
    return render(request , 'userUpdateProfile.html' , context)

NewIntense/account/views/partnerView.py
from ..models import User
from django.contrib.auth import login
from ..forms import partnerRegForm,EditProfileForm , EditPartnerProfile
from django.views.generic import CreateView
from django.shortcuts import render , redirect

class partnerReg(CreateView):
    model = User
    form_class = partnerRegForm
    template_name = 'partnerReg.html'

    def get_context_data(self , **kwargs):
        kwargs['user_type'] = 'partner'
        return super().get_context_data(**kwargs)

    def form_valid(self , form):
        user = form.save()
        return redirect('account:loginp')

def partnerUpdate(request):
    if request.method == 'POST':
        u_form = EditProfileForm(request.POST , instance = request.user)
        p_form = EditPartnerProfile(request.POST, instance = request.user.partner)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            return redirect('account:partner_dash')
    else:
        u_form = EditProfileForm(instance = request.user)
        p_form = EditPartnerProfile(instance = request.user.partner)
     
    context = {
        'u_form' : u_form,
        'p_form' : p_form
    }
    
    return render(request , 'userUpdatePartner.html' , context)

NewIntense/account/templates/candidateDash.html
{% load static %}
<!DOCTYPE html>
<head>
  <title>intense placement</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/dashStyle.css' %}">
<link rel="stylesheet" href="{% static 'styles/bootstrap-4.5.0/css/bootstrap.css' %}">
<link href="{% static 'plugins/fontawesome-free-5.13.0-web/css/fontawesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/fontawesome-free-5.13.0-web/css/brands.css' %}" rel="stylesheet">
<link href="{% static 'plugins/fontawesome-free-5.13.0-web/css/solid.css' %}" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" ></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" ></script>
<script src="{% static 'styles/bootstrap-4.5.0/js/bootstrap.min.js' %}" ></script>

    </head>
<body>
      
  <section id="header">
    <div class="menu-bar">
      <nav class="navbar navbar-expand-lg navbar-light ">
        <a class="navbar-brand" href="#">
          <img src="{% static 'img/ipLogo.png' %}">
        </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto" >
              <li class="nav-item ">
                <a class="nav-link " href="{% url 'account:logout' %}">Logout</a>
              </li>
            </ul>
          </div>
      </nav>
    </div>
  </section>
<br>
<div class="search-job text-center">
  <div>
      <h1 class="text-center text-white">Welcome {{user.username}}</h1>
  </div>
</div>
<div class="card-deck" >
  <div class="card border-info shadow p-3 mb-5 rounded" style="height:11rem;">
    <i class="card-img-top fas fa-home fa-5x "></i>
    <div class="card-body">
    <h5 class="card-title text-center"><a href="{% url 'main:homepage' %}">Homepage</a></h5>
    </div>
  </div>
  <div class="card border-info shadow p-3 mb-5 rounded " style="height:11rem;">
    <i class=" card-img-top fas fa-check fa-5x"></i>
    <div class="card-body">
      <h5 class="card-title text-center"><a href="{% url 'account:candapply' %}"></i> Jobs Applied</a></h5>
      </div>
  </div>
  <div class="card border-info shadow p-3 mb-5 rounded " style="height:11rem;">
    <i class=" card-img-top fab fa-black-tie fa-5x"></i>
    <div class="card-body">
      <h5 class="card-title text-center"><a href="{% url 'main:jobs' %}">  New Jobs</a></h5>
    </div>
  </div>
  <div class="card border-info shadow p-3 mb-5 rounded" style="height:11rem;">
    <i class=" card-img-top fas fa-pencil-alt fa-5x"></i>
    <div class="card-body">
      <h5 class="card-title text-center"><a href="{% url 'account:updateCandidate' %}"> Update Information</a></h5>
    </div>
  </div>
  <div class="card border-info shadow p-3 mb-5 rounded "style="height:11rem;">
    <i class=" card-img-top fas fa-phone fa-5x"></i>
    <div class="card-body">
      <h5 class="card-title text-center"><a href="{% url 'main:contact' %}"> Contact us </a></h5>
    </div>
  </div>
</div>
<footer class="page-footer font-small pt-4 pl-md-5">
    <div class="container-fluid text-center text-md-left">
      <div class="row">
        <div class="col-md-4 mt-md-0 mt-4 text-left" >
          <h5 class="text-uppercase" id="desc">Intense Placement</h5>
          <p id = "desc">Our Comapny provides you hastle free recruiting and save candidates from being cheated .Our main motto is to save each and every candidate from being cheated by fraud consultants or recruiters who asks money before getting the job. </p>
        </div>
        <!-- <hr class="clearfix w-100 d-md-none pb-3"> -->
        <div class="col-md-4 d-none d-lg-block d-xl-block text-center" >
          <h5 class="text-uppercase">Quick Links</h5>
          <ul class="list-unstyled">
            <li>
              <a href="{% url 'main:homepage' %}">Home</a>
            </li>
            <li>
              <a href="/contact/">Contact us</a>
            </li>
            <li>
              <a href="/about/">About us</a>
            </li>
            <li>
              <a href="/faq/">FAQs</a>
            </li>
            
          </ul>
        </div> 
        <div class="col-3 col-md-4 pl-md-4 d-none d-lg-block d-xl-block text-left">
          <h5 class="text-uppercase">Intense Placement </h5>
         <!--  <p>Subscribe to kormosala Pacific newsletter to get thelatest jobs posted, candidates, and other latestnews stay update.</p>
          <form id = "subs">
            <div class="field">
                <div class="input-group">
                    <input type="email" name="EMAIL" class="form-control" placeholder="Email Address...">
                    <span class="input-group-btn">
                        <button class="btn btn-submit" type= "submit">
                            <i class="fa fa-envelope-o"></i>
                        </button>
                    </span>
                </div>
            </div>
          </form> -->
          <p id = "desc">Our Comapny is creating Entrepreneurs.Because of our portal we are connecting many of the Genuine Consultants , Recruiters or Freelancers to Big MNC's which previously they don't get empanel with,because of their major compliance issue . </p>
        </div>
      </div>
    </div>
    <div class="container " style="height: 100px;">
        <div class="row">
            <div class="col-md-12 py-3">
            <h5 class= "pb-2 text-center">Follow Us</h5>
            <div class="mb-2 text-center">
              <a href = "https://www.facebook.com/Intense-Placement-Private-Limited-102928834808269/" class="fb-ic" style="color: rgb(255, 255, 255);">
                <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
              </a>
              <a href = "#" class="tw-ic" style="color:  rgb(255, 255, 255);">
                <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
              </a>
              <a href = "https://www.linkedin.com/company/intense-placement-private-limited" class="li-ic" style="color:  rgb(255, 255, 255);">
                <i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
              </a>
              <a href = "https://www.instagram.com/invites/contact/?i=zmndwoirzzee&utm_content=hftfvyr" class="ins-ic" style="color:  rgb(255, 255, 255);">
                <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
              </a>
            </div>
          </div>
        </div>
    </div>
    <div class="footer-copyright text-center py-2">
      <h6> <a href="mailto:devvarrior@gmail.com" class="text-white" style="float: left;"><i class="fas fa-code"></i> Website credits : Devvarrior <i class="fas fa-code"></i></a> <p style="float: right;">© 2020 Copyright:Intense Placement</p></h6>
      <br>
    </div>
</footer>
  <!-- <div> -->
</body>
</html> 
    

NewIntense/account/templates/partnerDash.html
{% load static %}
<!DOCTYPE html>
<head>
  <title>intense placement</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/dashStyle.css' %}">
<link rel="stylesheet" href="{% static 'styles/bootstrap-4.5.0/css/bootstrap.css' %}">
<link href="{% static 'plugins/fontawesome-free-5.13.0-web/css/fontawesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/fontawesome-free-5.13.0-web/css/brands.css' %}" rel="stylesheet">
<link href="{% static 'plugins/fontawesome-free-5.13.0-web/css/solid.css' %}" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" ></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" ></script>
<script src="{% static 'styles/bootstrap-4.5.0/js/bootstrap.min.js' %}" ></script>

    </head>
<body>
      
  <section id="header">
    <div class="menu-bar">
      <nav class="navbar navbar-expand-lg navbar-light ">
        <a class="navbar-brand" href="#">
          <img src="{% static 'img/ipLogo.png' %}">
        </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto" >
              <li class="nav-item ">
                <a class="nav-link " href="{% url 'account:logout' %}">Logout</a>
              </li>
            </ul>
          </div>
      </nav>
    </div>
  </section>
<br>
      <div class="search-job text-center">
  <div>
      <h1 class="text-center text-white">Welcome {{user.username}}</h1>
    </div>
  
  </div>
 

  
    
    <div class="card-deck" >
      <div class="card border-info shadow p-3 mb-5 rounded" style="height:11rem;">
        <i class="card-img-top fas fa-home fa-5x "></i>
        <div class="card-body">
        <h5 class="card-title text-center"><a href="{% url 'main:homepage' %}">Homepage</a></h5>
        </div>
      </div>
      <div class="card border-info shadow p-3 mb-5 rounded " style="height:11rem;">
        <i class=" card-img-top fas fa-check fa-5x"></i>
        <div class="card-body">
          <h5 class="card-title text-center"><a href="{% url 'account:patapply' %}">Your Applications</a></h5>
          </div>
      </div>
      <div class="card border-info shadow p-3 mb-5 rounded " style="height:11rem;">
        <i class=" card-img-top fab fa-black-tie fa-5x"></i>
        <div class="card-body">
          <h5 class="card-title text-center"><a href="{% url 'main:patcomm' %}"> Vaccancies</a></h5>
          </div>
      </div>
      <div class="card border-info shadow p-3 mb-5 rounded" style="height:11rem;">
        <i class=" card-img-top fas fa-pencil-alt fa-5x"></i>
        <div class="card-body">
          <h5 class="card-title text-center"><a href="{% url 'account:partnerupdate' %}"> Update Information</a></h5>
        </div>
      </div>
      <div class="card border-info shadow p-3 mb-5 rounded "style="height:11rem;">
        <i class=" card-img-top fas fa-phone fa-5x"></i>
        <div class="card-body">
          <h5 class="card-title text-center"><a href="{% url 'main:contact' %}"> Contact us </a></h5>
        </div>
      </div>
    </div>
    <div>
      <footer class="page-footer font-small pt-4 pl-md-5">
    <div class="container-fluid text-center text-md-left">
      <div class="row">
        <div class="col-md-4 mt-md-0 mt-4 text-left" >
          <h5 class="text-uppercase" id="desc">Intense Placement</h5>
          <p id = "desc">Our Comapny provides you hastle free recruiting and save candidates from being cheated .Our main motto is to save each and every candidate from being cheated by fraud consultants or recruiters who asks money before getting the job. </p>
        </div>
        <!-- <hr class="clearfix w-100 d-md-none pb-3"> -->
        <div class="col-md-4 d-none d-lg-block d-xl-block text-center" >
          <h5 class="text-uppercase">Quick Links</h5>
          <ul class="list-unstyled">
            <li>
              <a href="{% url 'main:homepage' %}">Home</a>
            </li>
            <li>
              <a href="/contact/">Contact us</a>
            </li>
            <li>
              <a href="/about/">About us</a>
            </li>
            <li>
              <a href="/faq/">FAQs</a>
            </li>
            
          </ul>
        </div> 
        <div class="col-3 col-md-4 pl-md-4 d-none d-lg-block d-xl-block text-left">
          <h5 class="text-uppercase">Intense Placement </h5>
          <p id = "desc">Our Comapny is creating Entrepreneurs.Because of our portal we are connecting many of the Genuine Consultants , Recruiters or Freelancers to Big MNC's which previously they don't get empanel with,because of their major compliance issue . </p>
        </div>
      </div>
    </div>
    <div class="container " style="height: 100px;">
        <div class="row">
            <div class="col-md-12 py-3">
            <h5 class= "pb-2 text-center">Follow Us</h5>
            <div class="mb-2 text-center">
              <a href = "https://www.facebook.com/Intense-Placement-Private-Limited-102928834808269/" class="fb-ic" style="color: rgb(255, 255, 255);">
                <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
              </a>
              <a href = "#" class="tw-ic" style="color:  rgb(255, 255, 255);">
                <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
              </a>
              <a href = "https://www.linkedin.com/company/intense-placement-private-limited" class="li-ic" style="color:  rgb(255, 255, 255);">
                <i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
              </a>
              <a href = "https://www.instagram.com/invites/contact/?i=zmndwoirzzee&utm_content=hftfvyr" class="ins-ic" style="color:  rgb(255, 255, 255);">
                <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
              </a>
            </div>
          </div>
        </div>
    </div>
    <div class="footer-copyright text-center py-2">
      <h6> <a href="mailto:devvarrior@gmail.com" class="text-white" style="float: left;"><i class="fas fa-code"></i> Website credits : Devvarrior <i class="fas fa-code"></i></a> <p style="float: right;">© 2020 Copyright:Intense Placement</p></h6>
      <br>
    </div>
</footer>
    </body>
    </html> 
    